FROM postgres:16-alpine

# Install pgvector
RUN apk add --no-cache git gcc musl-dev postgresql-dev clang llvm make && \
    git clone https://github.com/pgvector/pgvector.git /tmp/pgvector && \
    cd /tmp/pgvector && \
    make && \
    make install && \
    rm -rf /tmp/pgvector && \
    apk del git gcc musl-dev postgresql-dev clang llvm make
