[build]
builder = "nixpacks"
buildCommand = "pnpm prisma generate && pnpm nx build api"

[deploy]
startCommand = "node services/api/dist/main.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
